services:
  bot:
    build: .
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    user: postgres
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  pgdata: {}
